pub mod commands;
pub mod events;
pub mod types;

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

pub fn builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::subscribe_agent_chunks,
            commands::subscribe_pty,
            commands::subscribe_diffs
        ])
        .events(tauri_specta::collect_events![events::StateChanged])
}

pub fn export_bindings(builder: &Builder) {
    builder
        .export(
            Typescript::new()
                .header("// @ts-nocheck - generated by tauri-specta; do not edit.\n")
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/ipc/bindings.ts",
        )
        .expect("failed to export TypeScript IPC bindings");
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_typescript_bindings() {
        super::export_bindings(&super::builder());
    }
}
