pub mod commands;
pub mod events;
pub mod subscriptions;
pub mod types;

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

pub fn builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::reload_environment,
            commands::fetch_on_focus,
            commands::get_metrics,
            commands::subscribe_agent_chunks,
            commands::subscribe_agent_events,
            commands::detect_engines,
            commands::send_thread_prompt,
            commands::cancel_thread_turn,
            commands::pause_thread,
            commands::resume_thread,
            commands::resolve_approval,
            commands::resolve_all_approvals,
            commands::subscribe_pty,
            commands::subscribe_diffs,
            commands::unsubscribe,
            commands::refresh_workspace_diff,
            commands::set_workspace_diff_base,
            commands::start_streaming_spike,
            commands::summarise_workspace,
            commands::set_github_token,
            commands::clear_github_token,
            commands::sync_pull_requests,
            commands::list_repo_branches,
            commands::create_workspace,
            commands::create_review_workspace,
            commands::submit_workspace_review,
            commands::retry_workspace_provisioning,
            commands::skip_workspace_provisioning_setup,
            commands::join_workspace_thread,
            commands::rename_workspace,
            commands::switch_workspace_branch,
            commands::pull_workspace,
            commands::rebase_workspace,
            commands::push_workspace_branch,
            commands::draft_pr_why,
            commands::create_workspace_pull_request,
            commands::abort_workspace_git,
            commands::create_workspace_branch,
            commands::get_teardown_preview,
            commands::teardown_workspace,
            commands::control_workspace_app,
            commands::set_repo_run_command,
            commands::set_repo_setup_commands,
            commands::add_repo,
            commands::remove_repo,
            commands::test_repo_setup,
            commands::set_setting,
            commands::send_workspace_findings,
            commands::create_scratch,
            commands::end_scratch
        ])
        .events(tauri_specta::collect_events![
            events::StateChanged,
            events::WorkspaceStatusChanged,
            events::ToastRaised
        ])
}

pub fn export_bindings(builder: &Builder) {
    builder
        .export(
            Typescript::new()
                .header("// @ts-nocheck - generated by tauri-specta; do not edit.\n")
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/ipc/bindings.ts",
        )
        .expect("failed to export TypeScript IPC bindings");
}

#[cfg(test)]
mod tests {
    /// Tauri rejects any command missing from the allowlist, and the browser harness can't see it.
    #[test]
    fn every_command_is_allowlisted() {
        let registered = include_str!("mod.rs")
            .split(".events(")
            .next()
            .unwrap()
            .split("commands::")
            .skip(1)
            .map(|rest| {
                rest.split(|c: char| !(c.is_alphanumeric() || c == '_'))
                    .next()
                    .unwrap()
            })
            .filter(|name| !name.is_empty())
            .collect::<Vec<_>>();
        let allowlist = include_str!("../../permissions/ipc.toml");
        let missing: Vec<_> = registered
            .into_iter()
            .filter(|name| !allowlist.contains(&format!("\"{name}\"")))
            .collect();
        assert!(missing.is_empty(), "add to permissions/ipc.toml: {missing:?}");
    }

    #[test]
    fn export_typescript_bindings() {
        super::export_bindings(&super::builder());
    }
}
