pub mod commands;
pub mod events;
pub mod types;

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

pub fn builder() -> Builder {
    Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::get_snapshot,
            commands::reload_environment,
            commands::fetch_on_focus,
            commands::get_metrics,
            commands::subscribe_agent_chunks,
            commands::subscribe_agent_events,
            commands::detect_engines,
            commands::resolve_approval,
            commands::subscribe_pty,
            commands::subscribe_diffs,
            commands::start_streaming_spike,
            commands::summarise_workspace,
            commands::set_github_token,
            commands::clear_github_token,
            commands::sync_pull_requests,
            commands::list_repo_branches,
            commands::create_workspace,
            commands::retry_workspace_provisioning,
            commands::skip_workspace_provisioning_setup,
            commands::join_workspace_thread,
            commands::rename_workspace,
            commands::get_teardown_preview,
            commands::teardown_workspace
        ])
        .events(tauri_specta::collect_events![
            events::StateChanged,
            events::WorkspaceStatusChanged,
            events::ToastRaised
        ])
}

pub fn export_bindings(builder: &Builder) {
    builder
        .export(
            Typescript::new()
                .header("// @ts-nocheck - generated by tauri-specta; do not edit.\n")
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/ipc/bindings.ts",
        )
        .expect("failed to export TypeScript IPC bindings");
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_typescript_bindings() {
        super::export_bindings(&super::builder());
    }
}
