// @ts-nocheck - generated by tauri-specta; do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSnapshot() : Promise<Result<Snapshot, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reloadEnvironment() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_environment") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchOnFocus() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_on_focus") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetrics() : Promise<Result<MemorySample, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of agent message chunks for one thread.
 */
async subscribeAgentChunks(threadId: string, channel: TAURI_CHANNEL<AgentChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_agent_chunks", { threadId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectEngines() : Promise<Result<EngineStatus[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_engines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(id: string, approved: boolean) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_approval", { id, approved }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of PTY output for a workspace's run/setup log.
 */
async subscribePty(workspaceId: string, channel: TAURI_CHANNEL<PtyChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_pty", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of live diff updates for a worktree.
 */
async subscribeDiffs(workspaceId: string, channel: TAURI_CHANNEL<DiffUpdate>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_diffs", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spike 5: stream agent chunks (~60hz) and PTY lines (100/s) for a few seconds.
 */
async startStreamingSpike(agent: TAURI_CHANNEL<AgentChunk>, pty: TAURI_CHANNEL<PtyChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_streaming_spike", { agent, pty }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
stateChanged: StateChanged,
toastRaised: ToastRaised,
workspaceStatusChanged: WorkspaceStatusChanged
}>({
stateChanged: "state-changed",
toastRaised: "toast-raised",
workspaceStatusChanged: "workspace-status-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type AgentChunk = { threadId: string; text: string }
export type AppView = "homebase" | { workspace: { id: string } } | "settings"
export type ApprovalRow = { id: string; threadId: string; status: string; tool: string; payload: string }
export type DiffFile = { path: string; added: number; deleted: number; hunks: DiffHunk[] }
export type DiffHunk = { header: string; body: string }
export type DiffUpdate = { workspaceId: string; path: string; diff: WorktreeDiff | null }
/**
 * Engines Harness can spawn. Launch is Claude and Cursor; Codex and Gemini share ACP.
 */
export type EngineKind = "claude" | "cursor" | "codex" | "gemini"
export type EngineStatus = { kind: EngineKind; installed: boolean; binary: string | null; version: string | null; signedIn: boolean | null }
/**
 * Shared error type for the Rust core. Serialised as a tagged union so the
 * generated TypeScript bindings stay in lockstep with Rust.
 */
export type Error = { kind: "Io"; message: string } | { kind: "ShellEnv"; message: string } | { kind: "Git"; message: string } | { kind: "Workspace"; message: string } | { kind: "Engine"; message: string } | { kind: "Approval"; message: string } | { kind: "Mcp"; message: string } | { kind: "Process"; message: string } | { kind: "Github"; message: string } | { kind: "Llm"; message: string } | { kind: "Store"; message: string } | { kind: "Metrics"; message: string } | { kind: "NotImplemented"; message: string }
export type FindingRow = { id: string; workspaceId: string; severity: string; title: string; file: string | null; line: number | null; explanation: string; status: string; commitSha: string | null }
export type MemorySample = { totalBytes: number; perWorkspace: WorkspaceMemory[] }
export type PersistedSnapshot = { settings: SettingRow[]; repos: RepoRecord[]; workspaces: WorkspaceRow[]; threads: ThreadRow[]; timeline: ThreadEventRow[]; approvals: ApprovalRow[]; findings: FindingRow[]; pullRequests: PrRow[] }
export type PrRow = { id: string; repoId: string | null; number: number; title: string; payload: string }
export type PtyChunk = { workspaceId: string; line: string }
export type RepoRecord = { id: string; path: string; name: string; defaultBranch: string | null; setupCommands: string; runCommand: string | null }
export type SettingRow = { key: string; value: string }
export type Snapshot = { version: number; view: AppView; persisted: PersistedSnapshot; workspaces: WorkspaceRecord[]; memory: MemorySample | null; 
/**
 * In-memory broker queue (may exceed persisted pending rows).
 */
pendingLiveApprovals: number }
export type StateChangeKind = "workspaceStatus" | "approvalCounts" | "prSync" | "toast" | "behindCounts" | "metrics" | "environment"
/**
 * Low-volume core → UI notification. `version` is monotonic; a gap means the
 * webview should call `get_snapshot` and replace local state.
 */
export type StateChanged = { version: number; kind: StateChangeKind }
export type ThreadEventRow = { id: number; threadId: string; seq: number; kind: string; payload: string }
export type ThreadRow = { id: string; workspaceId: string; title: string; engine: string; sessionId: string | null; status: string; usedTokens: number | null; contextSize: number | null; costUsd: number | null; transcriptReadonly: boolean }
export type ToastPart = { type: "text"; value: string } | { type: "code"; value: string }
export type ToastRaised = { payload: ToastRaisedPayload }
export type ToastRaisedPayload = { tone: ToastTone; parts: ToastPart[]; workspaceId: string | null }
export type ToastTone = "ok" | "bad" | "default"
/**
 * Workspace lifecycle. `ready` is idle with no threads; running/idle/waiting
 * describe activity after provisioning.
 */
export type WorkspaceLifecycle = "creating" | "provisioning" | "ready" | "running" | "idle" | "waiting" | "tearingDown" | "gone" | "provisioningFailed"
export type WorkspaceMemory = { workspaceId: string; bytes: number }
export type WorkspaceRecord = { id: string; repoId: string; repoPath: string; name: string; branch: string; base: string; worktreePath: string; status: WorkspaceLifecycle; version: number }
export type WorkspaceRow = { id: string; repoId: string; name: string; branch: string; worktreePath: string; status: string }
export type WorkspaceStatusChanged = { version: number; workspaceId: string; status: WorkspaceLifecycle }
export type WorktreeDiff = { workspaceId: string; files: DiffFile[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
