// @ts-nocheck - generated by tauri-specta; do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSnapshot() : Promise<Result<Snapshot, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reloadEnvironment() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_environment") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchOnFocus() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_on_focus") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMetrics() : Promise<Result<MemorySample, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of agent message chunks for one thread.
 */
async subscribeAgentChunks(threadId: string, channel: TAURI_CHANNEL<AgentChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_agent_chunks", { threadId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of normalised agent events for one thread.
 */
async subscribeAgentEvents(threadId: string, channel: TAURI_CHANNEL<AgentEvent>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_agent_events", { threadId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectEngines() : Promise<Result<EngineStatus[], Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_engines") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendThreadPrompt(threadId: string, text: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_thread_prompt", { threadId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelThreadTurn(threadId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_thread_turn", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseThread(threadId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_thread", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeThread(threadId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_thread", { threadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(id: string, approved: boolean, denyReason: string | null) : Promise<Result<ResolveApprovalResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_approval", { id, approved, denyReason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveAllApprovals(threadId: string, approved: boolean, denyReason: string | null) : Promise<Result<ResolveApprovalResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_all_approvals", { threadId, approved, denyReason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of PTY output for a workspace's run/setup log.
 */
async subscribePty(workspaceId: string, channel: TAURI_CHANNEL<PtyChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_pty", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of live diff updates for a worktree.
 */
async subscribeDiffs(workspaceId: string, channel: TAURI_CHANNEL<DiffUpdate>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_diffs", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Force-refresh the live diff snapshot for one workspace (branch switch, pull, etc.).
 */
async refreshWorkspaceDiff(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_workspace_diff", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Approve stages the file; reject discards worktree edits for that path.
 */
async reviewWorktreeFile(workspaceId: string, path: string, decision: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_worktree_file", { workspaceId, path, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spike 5: stream agent chunks (~60hz) and PTY lines (100/s) for a few seconds.
 */
async startStreamingSpike(agent: TAURI_CHANNEL<AgentChunk>, pty: TAURI_CHANNEL<PtyChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_streaming_spike", { agent, pty }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generate or return a cached workspace card summary (debounced LLM + local fallback).
 */
async summariseWorkspace(workspaceId: string) : Promise<Result<WorkspaceSummaryResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarise_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setGithubToken(token: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_github_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearGithubToken() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_github_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncPullRequests() : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_pull_requests") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRepoBranches(repoId: string) : Promise<Result<RepoBranchesResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_repo_branches", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(input: CreateWorkspaceInput) : Promise<Result<CreateWorkspaceResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryWorkspaceProvisioning(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_workspace_provisioning", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skipWorkspaceProvisioningSetup(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skip_workspace_provisioning_setup", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinWorkspaceThread(input: JoinWorkspaceThreadInput) : Promise<Result<JoinWorkspaceThreadResult, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_workspace_thread", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWorkspace(input: RenameWorkspaceInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_workspace", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchWorkspaceBranch(input: SwitchWorkspaceBranchInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_workspace_branch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pullWorkspace(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pull_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rebaseWorkspace(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebase_workspace", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pushWorkspaceBranch(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_workspace_branch", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortWorkspaceGit(workspaceId: string) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_workspace_git", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspaceBranch(input: CreateWorkspaceBranchInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace_branch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTeardownPreview(workspaceId: string) : Promise<Result<TeardownPreview, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_teardown_preview", { workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async teardownWorkspace(input: TeardownInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("teardown_workspace", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async controlWorkspaceApp(input: ControlWorkspaceAppInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("control_workspace_app", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRepoRunCommand(input: SetRepoRunCommandInput) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_run_command", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
stateChanged: StateChanged,
toastRaised: ToastRaised,
workspaceStatusChanged: WorkspaceStatusChanged
}>({
stateChanged: "state-changed",
toastRaised: "toast-raised",
workspaceStatusChanged: "workspace-status-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type AgentChunk = { threadId: string; text: string }
/**
 * One internal event every adapter translates into (COR-56).
 */
export type AgentEvent = { type: "sessionStarted"; session_id: string } | { type: "messageChunk"; role: MessageRole; text: string } | { type: "toolCall"; id: string; title: string; name: string | null; kind: ToolKind; status: ToolCallStatus; locations: string[]; detail: string | null } | { type: "plan"; entries: PlanStep[] } | { type: "permission"; id: string; tool_call_id: string | null; title: string; tool_name: string; kind: ToolKind; detail: string | null; auto_approved: boolean } | { type: "currentTool"; id: string | null; title: string } | { type: "usage"; used_tokens: number; context_size: number; cost_usd: number | null } | { type: "turnEnd"; stop_reason: string; error: string | null } | { type: "engineExited"; code: number | null }
export type AppView = "homebase" | { workspace: { id: string } } | "settings"
export type ApprovalRow = { id: string; threadId: string; status: string; tool: string; payload: string }
export type ControlWorkspaceAppInput = { workspaceId: string; action: WorkspaceAppControlAction }
export type CreateWorkspaceBranchInput = { workspaceId: string; branch: string }
export type CreateWorkspaceInput = { repoId: string; name: string; branch: string; base: string; engine: string; goal: string }
export type CreateWorkspaceResult = { workspaceId: string }
export type DiffFile = { path: string; added: number; deleted: number; hunks: DiffHunk[] }
export type DiffHunk = { header: string; body: string }
export type DiffUpdate = { workspaceId: string; path: string; diff: WorktreeDiff | null }
/**
 * Engines Harness can spawn. Launch is Claude and Cursor; Codex and Gemini share ACP.
 */
export type EngineKind = "claude" | "cursor" | "codex" | "gemini"
export type EngineStatus = { kind: EngineKind; installed: boolean; binary: string | null; version: string | null; signedIn: boolean | null }
/**
 * Shared error type for the Rust core. Serialised as a tagged union so the
 * generated TypeScript bindings stay in lockstep with Rust.
 */
export type Error = { kind: "Io"; message: string } | { kind: "ShellEnv"; message: string } | { kind: "Git"; message: string } | { kind: "GitConflict"; message: { operation: string; paths: string[] } } | { kind: "Workspace"; message: string } | { kind: "Engine"; message: string } | { kind: "Approval"; message: string } | { kind: "Mcp"; message: string } | { kind: "Process"; message: string } | { kind: "Github"; message: string } | { kind: "Llm"; message: string } | { kind: "Store"; message: string } | { kind: "Metrics"; message: string } | { kind: "NotImplemented"; message: string }
export type FindingRow = { id: string; workspaceId: string; severity: string; title: string; file: string | null; line: number | null; explanation: string; status: string; commitSha: string | null }
export type GitConflictOperation = "merge" | "rebase"
export type GitConflictState = { operation: GitConflictOperation; paths: string[] }
export type JoinWorkspaceThreadInput = { workspaceId: string; title: string; engine: string }
export type JoinWorkspaceThreadResult = { threadId: string }
export type MemorySample = { totalBytes: number; perWorkspace: WorkspaceMemory[] }
export type MessageRole = "user" | "agent" | "thought"
export type PersistedSnapshot = { settings: SettingRow[]; repos: RepoRecord[]; workspaces: WorkspaceRow[]; threads: ThreadRow[]; timeline: ThreadEventRow[]; approvals: ApprovalRow[]; findings: FindingRow[]; pullRequests: PrRow[] }
export type PlanStep = { content: string; status: string }
export type PrRow = { id: string; repoId: string | null; number: number; title: string; payload: string }
export type PtyChunk = { workspaceId: string; line: string }
export type RenameWorkspaceInput = { workspaceId: string; name: string }
export type RepoBranchesResult = { branches: string[] }
export type RepoRecord = { id: string; path: string; name: string; defaultBranch: string | null; setupCommands: string; runCommand: string | null }
export type ResolveApprovalResult = { focusComposer: boolean }
export type SetRepoRunCommandInput = { repoId: string; runCommand: string | null }
export type SettingRow = { key: string; value: string }
export type Snapshot = { version: number; view: AppView; persisted: PersistedSnapshot; workspaces: WorkspaceRecord[]; workspaceGit: WorkspaceGitRuntime[]; memory: MemorySample | null; 
/**
 * In-memory broker queue (may exceed persisted pending rows).
 */
pendingLiveApprovals: number; 
/**
 * True when a PAT is stored or `gh auth token` succeeds.
 */
githubAuthConfigured: boolean; 
/**
 * Unix seconds string from the last successful PR sync, if any.
 */
prSyncedAt: string | null; workspaceApps: WorkspaceAppRuntime[] }
export type StateChangeKind = "workspaceStatus" | "approvalCounts" | "prSync" | "toast" | "behindCounts" | "metrics" | "environment" | "workspaceApp"
/**
 * Low-volume core → UI notification. `version` is monotonic; a gap means the
 * webview should call `get_snapshot` and replace local state.
 */
export type StateChanged = { version: number; kind: StateChangeKind }
export type SwitchWorkspaceBranchInput = { workspaceId: string; branch: string }
export type TeardownDataLoss = { uncommittedFiles: number; unpushedCommits: number; hasDataLoss: boolean; warning: string | null }
export type TeardownInput = { workspaceId: string; deleteBranch: boolean }
export type TeardownPreview = { workspaceId: string; workspaceName: string; engineLabel: string; branch: string; worktreePath: string; appRunning: boolean; deleteBranchDefault: boolean; dataLoss: TeardownDataLoss }
export type ThreadEventRow = { id: number; threadId: string; seq: number; kind: string; payload: string }
export type ThreadRow = { id: string; workspaceId: string; title: string; engine: string; sessionId: string | null; status: string; usedTokens: number | null; contextSize: number | null; costUsd: number | null; transcriptReadonly: boolean }
export type ToastPart = { type: "text"; value: string } | { type: "code"; value: string }
export type ToastRaised = { payload: ToastRaisedPayload }
export type ToastRaisedPayload = { tone: ToastTone; parts: ToastPart[]; workspaceId: string | null }
export type ToastTone = "ok" | "bad" | "default"
export type ToolCallStatus = "pending" | "inProgress" | "completed" | "failed"
/**
 * ACP `ToolKind`, owned so adapters and IPC do not depend on the protocol crate.
 */
export type ToolKind = "read" | "edit" | "delete" | "move" | "search" | "execute" | "think" | "fetch" | "other"
export type WorkspaceAppControlAction = "run" | "restart" | "stop" | "clear"
export type WorkspaceAppRuntime = { workspaceId: string; status: WorkspaceAppStatus; port: number | null; exitCode: number | null }
export type WorkspaceAppStatus = "stopped" | "starting" | "running" | "crashed"
export type WorkspaceGitRuntime = { workspaceId: string; behind: number; ahead: number; conflict: GitConflictState | null }
/**
 * Workspace lifecycle. `ready` is idle with no threads; running/idle/waiting
 * describe activity after provisioning.
 */
export type WorkspaceLifecycle = "creating" | "provisioning" | "ready" | "running" | "idle" | "waiting" | "tearingDown" | "gone" | "provisioningFailed"
export type WorkspaceMemory = { workspaceId: string; bytes: number }
export type WorkspaceRecord = { id: string; repoId: string; repoPath: string; name: string; branch: string; base: string; worktreePath: string; status: WorkspaceLifecycle; version: number; activity: string; provStep: number; setupFailedCommand: string | null; setupFailedExitCode: number | null }
export type WorkspaceRow = { id: string; repoId: string; name: string; branch: string; worktreePath: string; status: string; createdAt: string; summary: string | null; summaryAt: string | null; summarySource: string; kind: string | null; prNumber: number | null; modifiedFiles: number; archivedAt: string | null }
export type WorkspaceStatusChanged = { version: number; workspaceId: string; status: WorkspaceLifecycle }
export type WorkspaceSummaryResult = { workspaceId: string; summary: string; summaryAt: string; summarySource: string; fromLlm: boolean }
export type WorktreeDiff = { workspaceId: string; files: DiffFile[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
