// @ts-nocheck - generated by tauri-specta; do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSnapshot() : Promise<Result<Snapshot, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of agent message chunks for one thread.
 */
async subscribeAgentChunks(threadId: string, channel: TAURI_CHANNEL<AgentChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_agent_chunks", { threadId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of PTY output for a workspace's run/setup log.
 */
async subscribePty(workspaceId: string, channel: TAURI_CHANNEL<PtyChunk>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_pty", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * High-volume ordered stream of live diff updates for a worktree.
 */
async subscribeDiffs(workspaceId: string, channel: TAURI_CHANNEL<DiffUpdate>) : Promise<Result<null, Error>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_diffs", { workspaceId, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
stateChanged: StateChanged
}>({
stateChanged: "state-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type AgentChunk = { threadId: string; text: string }
export type AppView = "homebase" | { workspace: { id: string } } | "settings"
export type DiffUpdate = { workspaceId: string; path: string }
/**
 * Shared error type for the Rust core. Serialised as a tagged union so the
 * generated TypeScript bindings stay in lockstep with Rust.
 */
export type Error = { kind: "Io"; message: string } | { kind: "ShellEnv"; message: string } | { kind: "Git"; message: string } | { kind: "Workspace"; message: string } | { kind: "Engine"; message: string } | { kind: "Approval"; message: string } | { kind: "Mcp"; message: string } | { kind: "Process"; message: string } | { kind: "Github"; message: string } | { kind: "Llm"; message: string } | { kind: "Store"; message: string } | { kind: "Metrics"; message: string } | { kind: "NotImplemented"; message: string }
export type PtyChunk = { workspaceId: string; line: string }
export type Snapshot = { version: number; view: AppView }
export type StateChangeKind = "workspaceStatus" | "approvalCounts" | "prSync" | "toast"
/**
 * Low-volume core → UI notification. `version` is monotonic; a gap means the
 * webview should call `get_snapshot` and replace local state.
 */
export type StateChanged = { version: number; kind: StateChangeKind }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
